linters:
  disable-all: true
  enable:
  # - errcheck
  - gosimple
  - govet
  - staticcheck
  - ineffassign
  - unused
  - asasalint
  - asciicheck
  - bidichk
  - bodyclose
  - cyclop
  - dupl
  - dogsled
  - durationcheck
  - errname
  # - errorlint
  - gofmt
  - misspell
  - unconvert
  - prealloc
  - exportloopref
  # - gocritic
  # - revive
  # - stylecheck
  # - wsl
  # - whitespace
  - zerologlint
  - wastedassign
  # - wrapcheck
  - usestdlibvars
  - unparam
  - tparallel
  # - testpackage
  - testableexamples
  - tenv
  - tagalign
  - sqlclosecheck

  
linters-settings:

  cyclop:
    max-complexity: 15
    skip-tests: true

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated
