name: Audit

on:
  pull_request:
  push:
    branches:
      - master

jobs:

  audit:
    runs-on: ubuntu-22.04
    env:
      GO111MODULE: on
    steps:
          
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21'

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build -v ./...

    # - name: golangci-lint
    #   uses: golangci/golangci-lint-action@v3
    #   with:
    #     version: v1.54

    - uses: KengoTODA/actions-setup-docker-compose@v1
      with:
        version: '2.14.2' # the full version of `docker-compose` command

    - name: Install make
      run: sudo apt install make curl

    - name: Run generate
      run: make generate

    - name: Run tests
      run: make test-integration-ci